services:
  notebook: 
    image: jupyter/base-notebook
    ports: 
      - 8888:8888
    volumes:
      - ./work:/user/home/joyvan
  py38:
      image: python:3.8
      volumes:
          - "./:/app"
      working_dir: "/app"
      command: sh -c "pip install --upgrade pip && \
          pip install -r requirements-dev.txt && \
          tox &&
          echo Completed run using $(python --version)"
  py39:
      extends:
          service: py38
      image: python:3.9
  py310:
      extends:
          service: py38
      image: python:3.10
  py311:
      extends:
          service: py38
      image: python:3.11
  py36:
      extends:
          service: py38
      image: python:3.6
  py37:
      extends:
          service: py38
      image: python:3.7
